#!/usr/bin/env bash
# tests/scaffold/run.sh
# Golden-file diff runner for scaffold-game-server.{sh,ps1}.
# Design Ref: §11.2 step 5, §8.3 (golden-file cases).
#
# Usage:
#   tests/scaffold/run.sh                          # run all cases via .sh
#   tests/scaffold/run.sh case-01-simple           # single case
#   tests/scaffold/run.sh --script ps1             # use PowerShell instead
#   tests/scaffold/run.sh --update-golden case-01-simple
#                                                  # capture sha256/tree baseline
#   tests/scaffold/run.sh --keep                   # keep tmpdirs on success
#
# Per-case schema:
#   <case>/input/args.txt           — one CLI arg per line, '{DEST}' placeholder
#   <case>/input/pre/               — optional: copied into <DEST> before scaffold
#   <case>/expected/exit-code.txt
#   <case>/expected/stderr-contains.txt   (optional)
#   <case>/expected/stdout-contains.txt   (optional)
#   <case>/expected/files-present.txt     (optional)
#   <case>/expected/files-absent.txt      (optional)
#   <case>/expected/sha256.txt            (case-01 only, generated by --update-golden)
#   <case>/expected/tree.txt              (case-01 only, generated by --update-golden)

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate self / repo
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SCAFFOLD_BASH="${REPO_ROOT}/scripts/scaffold-game-server.sh"
SCAFFOLD_PS1="${REPO_ROOT}/scripts/scaffold-game-server.ps1"

# ---------------------------------------------------------------------------
# Defaults / parse
# ---------------------------------------------------------------------------
FLAVOR="sh"
UPDATE_GOLDEN=0
KEEP_TMP=0
SELECTED_CASES=()

usage() {
  cat <<EOF
Usage: $0 [--script sh|ps1] [--update-golden] [--keep] [<case>...]

  --script sh|ps1   Which scaffold script to drive (default: sh).
  --update-golden   Regenerate sha256.txt + tree.txt for case-01.
  --keep            Keep working directories after success (debug).
  <case>            Run a single case directory (default: all case-* dirs).
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --script)         FLAVOR="$2"; shift 2 ;;
    --update-golden)  UPDATE_GOLDEN=1; shift ;;
    --keep)           KEEP_TMP=1; shift ;;
    -h|--help)        usage; exit 0 ;;
    --*)              echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
    *)                SELECTED_CASES+=("$1"); shift ;;
  esac
done

case "${FLAVOR}" in
  sh)
    if [ ! -x "${SCAFFOLD_BASH}" ]; then
      echo "error: ${SCAFFOLD_BASH} missing or not executable" >&2
      exit 5
    fi
    ;;
  ps1)
    if [ ! -f "${SCAFFOLD_PS1}" ]; then
      echo "error: ${SCAFFOLD_PS1} missing" >&2
      exit 5
    fi
    if ! command -v pwsh >/dev/null 2>&1; then
      echo "error: 'pwsh' not on PATH (PowerShell 7 required for --script ps1)" >&2
      exit 5
    fi
    ;;
  *)
    echo "error: --script must be 'sh' or 'ps1' (got: ${FLAVOR})" >&2
    exit 2
    ;;
esac

if [ ${#SELECTED_CASES[@]} -eq 0 ]; then
  while IFS= read -r d; do
    SELECTED_CASES+=("$(basename "${d}")")
  done < <(find "${SCRIPT_DIR}" -maxdepth 1 -mindepth 1 -type d -name 'case-*' | sort)
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
PASS_COUNT=0
FAIL_COUNT=0
FAILED_CASES=()

red()    { printf '\033[31m%s\033[0m' "$*"; }
green()  { printf '\033[32m%s\033[0m' "$*"; }
yellow() { printf '\033[33m%s\033[0m' "$*"; }

# Read non-empty, non-comment lines from a file. Empty if file missing.
read_lines() {
  local f="$1"
  [ -f "${f}" ] || return 0
  awk 'NF && $0 !~ /^[[:space:]]*#/' "${f}"
}

# Run one case. Returns 0 on pass, 1 on fail.
run_case() {
  local case_name="$1"
  local case_dir="${SCRIPT_DIR}/${case_name}"
  local input_dir="${case_dir}/input"
  local expected_dir="${case_dir}/expected"

  if [ ! -d "${case_dir}" ]; then
    echo "  $(red FAIL): case directory not found: ${case_dir}" >&2
    return 1
  fi
  if [ ! -f "${input_dir}/args.txt" ]; then
    echo "  $(red FAIL): missing ${input_dir}/args.txt" >&2
    return 1
  fi

  # Per-case tmpdir
  local tmp
  tmp="$(mktemp -d -t "scaffold-${case_name}.XXXXXX")"
  local dest="${tmp}/out"

  # Pre-populate dest if input/pre/ exists.
  if [ -d "${input_dir}/pre" ]; then
    mkdir -p "${dest}"
    # Use tar pipe for portable copy (Bash 3.2 compatible, no GNU cp -T).
    (cd "${input_dir}/pre" && tar -cf - .) | (cd "${dest}" && tar -xf -)
  fi

  # Build args array, substituting {DEST}.
  local -a args=()
  local line
  while IFS= read -r line; do
    [ -n "${line}" ] || continue
    case "${line}" in
      \#*) continue ;;
    esac
    line="${line//\{DEST\}/${dest}}"
    args+=("${line}")
  done < "${input_dir}/args.txt"

  # Invoke the scaffold script. Capture stdout, stderr, exit code.
  local stdout_file="${tmp}/stdout.log"
  local stderr_file="${tmp}/stderr.log"
  local rc=0
  if [ "${FLAVOR}" = "sh" ]; then
    set +e
    "${SCAFFOLD_BASH}" "${args[@]}" >"${stdout_file}" 2>"${stderr_file}"
    rc=$?
    set -e
  else
    # Translate POSIX-style flags to PowerShell switch names.
    local -a ps_args=()
    local a
    for a in "${args[@]}"; do
      case "${a}" in
        --force)      ps_args+=("-Force") ;;
        --no-git)     ps_args+=("-NoGit") ;;
        --skip-smoke) ps_args+=("-SkipSmoke") ;;
        --dry-run)    ps_args+=("-DryRun") ;;
        --help|-h)    ps_args+=("-Help") ;;
        *)            ps_args+=("${a}") ;;
      esac
    done
    set +e
    pwsh -NoProfile -File "${SCAFFOLD_PS1}" "${ps_args[@]}" >"${stdout_file}" 2>"${stderr_file}"
    rc=$?
    set -e
  fi

  # ---------- assertions ----------
  local case_pass=1
  local fail_reasons=()

  # exit code
  local expected_rc
  expected_rc="$(read_lines "${expected_dir}/exit-code.txt" | head -n1)"
  expected_rc="${expected_rc:-0}"
  if [ "${rc}" != "${expected_rc}" ]; then
    case_pass=0
    fail_reasons+=("exit code: expected ${expected_rc}, got ${rc}")
  fi

  # stdout substrings
  if [ -f "${expected_dir}/stdout-contains.txt" ]; then
    while IFS= read -r needle; do
      if ! grep -qF -- "${needle}" "${stdout_file}"; then
        case_pass=0
        fail_reasons+=("stdout missing: '${needle}'")
      fi
    done < <(read_lines "${expected_dir}/stdout-contains.txt")
  fi

  # stderr substrings
  if [ -f "${expected_dir}/stderr-contains.txt" ]; then
    while IFS= read -r needle; do
      if ! grep -qF -- "${needle}" "${stderr_file}"; then
        case_pass=0
        fail_reasons+=("stderr missing: '${needle}'")
      fi
    done < <(read_lines "${expected_dir}/stderr-contains.txt")
  fi

  # files-present
  if [ -f "${expected_dir}/files-present.txt" ]; then
    while IFS= read -r rel; do
      if [ ! -e "${dest}/${rel}" ]; then
        case_pass=0
        fail_reasons+=("missing file: ${rel}")
      fi
    done < <(read_lines "${expected_dir}/files-present.txt")
  fi

  # files-absent
  if [ -f "${expected_dir}/files-absent.txt" ]; then
    while IFS= read -r rel; do
      if [ -e "${dest}/${rel}" ]; then
        case_pass=0
        fail_reasons+=("unexpected file present: ${rel}")
      fi
    done < <(read_lines "${expected_dir}/files-absent.txt")
  fi

  # sha256 / tree (case-01 only, when expected files exist)
  if [ -f "${expected_dir}/sha256.txt" ] && [ "${UPDATE_GOLDEN}" -eq 0 ]; then
    local actual_sha256
    actual_sha256="$(compute_sha256 "${dest}")"
    if ! diff -u "${expected_dir}/sha256.txt" <(printf '%s\n' "${actual_sha256}") >"${tmp}/sha256.diff"; then
      case_pass=0
      fail_reasons+=("sha256 mismatch (see ${tmp}/sha256.diff)")
      KEEP_TMP=1
    fi
  fi
  if [ -f "${expected_dir}/tree.txt" ] && [ "${UPDATE_GOLDEN}" -eq 0 ]; then
    local actual_tree
    actual_tree="$(compute_tree "${dest}")"
    if ! diff -u "${expected_dir}/tree.txt" <(printf '%s\n' "${actual_tree}") >"${tmp}/tree.diff"; then
      case_pass=0
      fail_reasons+=("tree mismatch (see ${tmp}/tree.diff)")
      KEEP_TMP=1
    fi
  fi

  # update-golden mode: only writes baseline for case-01-simple
  if [ "${UPDATE_GOLDEN}" -eq 1 ] && [ "${case_name}" = "case-01-simple" ] && [ "${rc}" = "0" ]; then
    compute_sha256 "${dest}" > "${expected_dir}/sha256.txt"
    compute_tree   "${dest}" > "${expected_dir}/tree.txt"
    echo "  $(yellow updated): ${expected_dir}/sha256.txt"
    echo "  $(yellow updated): ${expected_dir}/tree.txt"
  fi

  # ---------- report ----------
  if [ "${case_pass}" -eq 1 ]; then
    echo "  $(green PASS): ${case_name}"
    if [ "${KEEP_TMP}" -eq 0 ]; then
      rm -rf "${tmp}"
    else
      echo "    (kept: ${tmp})"
    fi
    return 0
  else
    echo "  $(red FAIL): ${case_name}"
    local r
    for r in "${fail_reasons[@]}"; do
      echo "    - ${r}"
    done
    echo "    tmpdir: ${tmp}"
    echo "    stdout: ${stdout_file}"
    echo "    stderr: ${stderr_file}"
    return 1
  fi
}

# sha256 list, sorted, with paths relative to <root>.
# Excludes: .git/, *.sln, bin/, obj/, *.bak.
compute_sha256() {
  local root="$1"
  ( cd "${root}"
    find . -type f \
      ! -path './.git/*' \
      ! -path '*/bin/*' \
      ! -path '*/obj/*' \
      ! -name '*.sln' \
      ! -name '*.bak' \
    | LC_ALL=C sort \
    | while IFS= read -r f; do
        if command -v sha256sum >/dev/null 2>&1; then
          sha256sum "${f}"
        else
          # macOS fallback: shasum -a 256
          shasum -a 256 "${f}"
        fi
      done
  )
}

# Sorted relative file list. Same exclusion set as compute_sha256.
compute_tree() {
  local root="$1"
  ( cd "${root}"
    find . -type f \
      ! -path './.git/*' \
      ! -path '*/bin/*' \
      ! -path '*/obj/*' \
      ! -name '*.bak' \
    | LC_ALL=C sort
  )
}

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
echo "scaffold runner: flavor=${FLAVOR}, update-golden=${UPDATE_GOLDEN}, cases=${#SELECTED_CASES[@]}"

for case_name in "${SELECTED_CASES[@]}"; do
  if run_case "${case_name}"; then
    PASS_COUNT=$((PASS_COUNT + 1))
  else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAILED_CASES+=("${case_name}")
  fi
done

echo
echo "── summary ──"
echo "  pass: ${PASS_COUNT}"
echo "  fail: ${FAIL_COUNT}"
if [ "${FAIL_COUNT}" -gt 0 ]; then
  echo "  failed cases:"
  for c in "${FAILED_CASES[@]}"; do echo "    - ${c}"; done
  exit 1
fi
exit 0
